name: streamlit_telco_customer_analytics
channels:
  - snowflake
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - snowflake-snowpark-python
  - streamlit
  - pandas
  - numpy
  - plotly
  - altair
  - requests
  - pyarrow