site_name: Snowflake Lab Platform
nav:
  - Welcome:
    - index.md
  - Lab Steps:
    - Logging_in.md
    - Unstructured Data Processing:
      - document_ai.md
      - sound_transcripts.md
      - search_service.md
    - Structured Data Processing:
      - market_place.md
      - analyst.md
      - analyst_2.md
    - Application:
      - agents.md     
site_url: ""
use_directory_urls: false
plugins:
  - macros:
      include_dir: include 
      on_error_fail: false
      on_undefined: keep
      verbose: true
  - dataopslive
  - search
  - offline
  - glightbox
  - search
  - print-site
theme:
  name: material
  features:
    - toc.integrate
    - content.tabs.link
    - content.code.copy
    - content.code.annotation
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.tracking
    - navigation.sections
    # - navigation.expand
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: light-blue
      accent: blue
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: light-blue
      accent: light-blue

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.blocks.html

extra_css:
  - stylesheets/extra.css
