name: app_environment
channels:
  - snowflake
dependencies:
  - python=3.11.*
  - snowflake-snowpark-python=1.29.1
  - snowflake.core=1.0.5
  - streamlit=1.42.0
  - plotly=5.24.1
  - streamlit-extras=0.4.0
